const GAME_STATUS = {
  WAITING_TO_START: "WAITING_TO_START",
  WAITING_RED_SPY_GIVE_CLUE: "WAITING_RED_SPY_GIVE_CLUE",
  WAITING_RED_TEAM_ANS: "WAITING_RED_TEAM_ANS",
  WAITING_BLUE_SPY_GIVE_CLUE: "WAITING_BLUE_SPY_GIVE_CLUE",
  WAITING_BLUE_TEAM_ANS: "WAITING_BLUE_TEAM_ANS",
  GAME_END: "GAME_END",
};

const TEAM = {
  RED: "RED",
  BLUE: "BLUE",
};

module.exports = { GAME_STATUS, TEAM };
